### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Jakov-Kusan** [Jakov-Kusan/file-word-counter#1]
File is not being closed

**Comment by jj-attaq** [comment]
Hi there, I'm pretty new to Go, so I hope this will help. Apparently when using ioutil.ReadFile you don't actually have to close the file as you would with os.Open().

https://forum.golangbridge.org/t/reading-a-text-file/3534 

I ran your program and didn't notice anything wrong when it ran. I haven't encountered memory leaks before, could you (for my own benefit) describe the problem in a bit more depth. I'd be happy to assist however I am able.

**Comment by Jakov-Kusan** [comment]
Thank you, I am also pretty new to go, I didn't know that I don't have to close the file. 
Thank you for helping me, I really appreciate it.

**Comment by jj-attaq** [comment]
No problem. Since we're both new perhaps we could work on something together. I have some ideas for your morse code project if you like.

Best of luck to you.

**Comment by Jakov-Kusan** [comment]
Sure, i'd love to work with you on something.
What kind of ideas do you have in mind, I would love to hear them.
I will try to add them them to the project if I can.
